---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  labels:
    argocd.argoproj.io/type: AoA
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gitops-ziichat-app/argo-config.git
    targetRevision: HEAD
    path: app-of-apps/apps/auto-discovery
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
