---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: addons
  labels:
    argocd.argoproj.io/type: AoA
  namespace: argocd
spec:
  project: addons
  sources:
    - repoURL: https://github.com/gitops-ziichat/argo-config.git
      targetRevision: HEAD
      path: app-of-apps/addons/vendor
    - repoURL: https://github.com/gitops-ziichat/argo-config.git
      targetRevision: HEAD
      path: app-of-apps/addons/auto-discovery
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
